# Generated by Django 3.2.6 on 2021-09-15 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_database_api', '0003_auto_20210915_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Звезда'),
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
